### ISSUE TITLE
Expected newline or end of document after a statement (at line 12, column 44)

### ISSUE THREAD

**Issue by kjetilk-kontali** [mpeteuil/poetry-dotenv-plugin#12]
Hi,

After installing `poetry-dotenv-plugin` for Poetry version 1.3.2 I get this error message when running `poetry self show plugins`:
> Expected newline or end of document after a statement (at line 12, column 44)

This is the output from `poetry self show plugins` before installing poetry-dotenv-plugin:
![image](https://user-images.githubusercontent.com/88441560/221374939-87ed279e-6396-4b8a-894e-27b7b287647c.png)

And after:
![image](https://user-images.githubusercontent.com/88441560/221374953-e7121cb4-9412-48c7-bb76-a516d4975fd4.png)

Poetry version: 1.3.2
OS: Windows 11 Pro

**Comment by guin0x** [comment]
I'm having the same issue with poetry 1.4.2 when I run `poetry self show`

**Comment by mpeteuil** [comment]
This appears to be an issue with Poetry (https://github.com/python-poetry/poetry/issues/7885) that has been [resolved as of the 1.5.0 release](https://github.com/python-poetry/poetry/blob/master/CHANGELOG.md#fixed-1).

**Comment by jairov-apptio** [comment]
Still happening to me in 1.6.1
