### ISSUE TITLE
Bash commands are not executed

### ISSUE THREAD

**Issue by casellimarco** [mpeteuil/poetry-dotenv-plugin#13]
Hi,

If I have a variable in `.env` that uses bash commands executions this is interpreted literally.

Ex:
``` export REPO_ROOT=$(pwd) ```

loads `REPO_ROOT` as literally `$(pwd)`, whereas running `source .env` loads the current path correctly.

**Comment by mpeteuil** [comment]
Hi,

This is a limitation of `python-dotenv`, which does not support subshells, presumably out of security concerns. You can see https://github.com/theskumar/python-dotenv/issues/402 for more information (including references to other related issues).

In your particular example though you may be able to get by with `export REPO_ROOT=${PWD}`.

**Comment by nicolas-graves** [comment]
Hi @casellimarco !

I couldn't find a solution for this, so I wrote one package that should be able to handle this right here: https://github.com/nicolas-graves/python-direnv

This is less safe than python-dotenv, but has a level of security by checking that you have indeed allowed the file to be run.

Contributions welcome !
