### ISSUE TITLE
The standard install command does not modify the `pyproject.toml`

### ISSUE THREAD

**Issue by tamireinhorn** [mpeteuil/poetry-dotenv-plugin#19]
Hello!

My poetry version: 1.5.1

Upon merely using: `poetry self add poetry-dotenv-plugin` doesn't modify my `pyproject.toml`.
This is how it looks after using it.
```
[tool.poetry]
name = "fakt"
version = "0.1.0"
description = ""
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
dbt-postgres = "^1.6.0"
pre-commit = "^3.3.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
```

Even when I use `poetry remove`, nothing changes. I'm unsure of how this should work.

**Comment by mpeteuil** [comment]
Hi @tamireinhorn! Which `pyproject.toml` are you looking at? Poetry plugins are installed globally, not per project, so you will not see them modify a `pyproject.toml` at the project level. If you run `poetry self show plugins` it will show you all the plugins that are installed. Internally Poetry tracks the plugins in its own `pyproject.toml`, which you can find in the [data directory](https://python-poetry.org/docs/configuration/#data-directory). If you inspect that and the corresponding lock file where they exist on your platform/machine, then you will see `poetry-dotenv-plugin` listed there.

**Comment by tamireinhorn** [comment]
Oh, really? I presumed it was self contained much like anything else. That's good to know. Sorry for the mixup.
