### ISSUE TITLE
Create a CI/CD process

### ISSUE THREAD

**Issue by mpeteuil** [mpeteuil/poetry-dotenv-plugin#2]
Once #1 is resolved, we'll need to integrate that into a CI/CD process so that it's easy to publish new releases through git tagging and [Github Actions](https://github.com/features/actions).

**Comment by bneijt** [comment]
I set up CI/CD publishing for my own poetry project like so: https://github.com/bneijt/poetry-lock-package/blob/main/.github/workflows/publish.yml

Feel free to copy-paste from there.

**Comment by mpeteuil** [comment]
Resolved via #7
