### ISSUE TITLE
Consider removing support for Python 3.7

### ISSUE THREAD

**Issue by AdrianDsg** [mpeteuil/poetry-dotenv-plugin#22]
Hi @mpeteuil,

I just discovered this great project. I got a few thoughts to share.

Python **3.7** has reached it's [end-of-life](https://devguide.python.org/versions/#unsupported-versions) on 2023-06-27 so I think there's no need to keep [building](https://github.com/mpeteuil/poetry-dotenv-plugin/blob/9b74d55e5468ad68a93614bf5a3523dfe5512cee/.github/workflows/build.yml#L20) the plugin for this Python version.

As mentioned in [README.md](https://github.com/mpeteuil/poetry-dotenv-plugin/blob/9b74d55e5468ad68a93614bf5a3523dfe5512cee/README.md?plain=1#L42) poetry has already dropped support for Python 3.7. I also wondered why **poetry 1.5.1** is used for releases but the **latest** version for building (except for Python 3.7).

https://github.com/mpeteuil/poetry-dotenv-plugin/blob/9b74d55e5468ad68a93614bf5a3523dfe5512cee/.github/workflows/release.yml#L25

https://github.com/mpeteuil/poetry-dotenv-plugin/blob/9b74d55e5468ad68a93614bf5a3523dfe5512cee/.github/workflows/build.yml#L36-L38

**Comment by mpeteuil** [comment]
Hi @AdrianDsg!

Thanks for the thoughts. There are a few reasons I see for maintaining Python 3.7 compatibility:

- This project has no reason to use features which are not supported in that version, so there is no pain being suffered from supporting 3.7 from that perspective.
- As you mentioned 3.7 is end-of-life, however that doesn't mean there isn't code out there using it. There is a lot of legacy code and this project existed before 3.7 was EOL, so it's probable that there are projects out there using this and also 3.7 that haven't been upgraded. This may not matter, depending on how poetry is installed.
- This project is not a library, so compatibility with user code does not need to be a consideration. The only compatibility that matters to this project is compatibility with Poetry.

For those reasons I don't think there is anything gained by dropping 3.7 support.

As for the release still using 1.5.1, that just hasn't been updated until now (#23). Thanks for pointing it out!

**Comment by AdrianDsg** [comment]
@mpeteuil Thanks for sharing these insights.
