### ISSUE TITLE
permission denied when installing more-itertools

### ISSUE THREAD

**Issue by bbbart** [mpeteuil/poetry-dotenv-plugin#9]
I'm relatively new to `poetry`. Installed `poetry` on my Arch machine using the package repository. I then created a project and added some packages to it, without any problems. The little script I wrote also runs just fine in the virtualenv.

I then ran `poetry self add poetry-dotenv-plugin`, which results in a permission denied error:

```
EnvCommandError

  Command ['/usr/bin/python', '/usr/lib/python3.10/site-packages/virtualenv/seed/wheels/embed/pip-22.0.4-py3-none-any.whl/pip', 'install', '--disable-pip-version-check', '--prefix', '/usr', '--upgrade', '--no-deps', '/home/bbbart/.cache/pypoetry/artifacts/25/9a/c4/c53a87a07fc57c9f3f6a37c82cc237c0f3fd30c1e7a0f67e98c32af5e8/more_itertools-8.14.0-py3-none-any.whl'] errored with the following return code 1, and output:
  Processing /home/bbbart/.cache/pypoetry/artifacts/25/9a/c4/c53a87a07fc57c9f3f6a37c82cc237c0f3fd30c1e7a0f67e98c32af5e8/more_itertools-8.14.0-py3-none-any.whl
  Installing collected packages: more-itertools
    Attempting uninstall: more-itertools
      Found existing installation: more-itertools 8.13.0
      Uninstalling more-itertools-8.13.0:
  ERROR: Could not install packages due to an OSError: [Errno 13] Permission denied: 'WHEEL'
  Consider using the `--user` option or check the permissions.
```

I quickly ran out of ideas on what to try next.

Perhaps someone here could point me in the right direction?

Feel free to direct me to another place that might be more appropriate for this question.

**Comment by bbbart** [comment]
I can see the command is trying to install a package somewhere below `/usr`, which my user of course has no permissions for. But how to avoid this? Or should I not have installed poetry through `pacman` in the first place, or try to find an Arch package for this plugin?

**Comment by mpeteuil** [comment]
I would recommend installing poetry [via the official installer](https://python-poetry.org/docs/#installing-with-the-official-installer) method that is mentioned in the Poetry documentation. I have confirmed that method works on the latest Arch. 

You're unlikely to be able to find an Arch package for this plugin, so if you wanted to go that route you'd probably have to create one yourself as I'm not that familiar with Arch. If you still want to stick with `pacman` then I think I'd need to know more details about how you installed poetry through `pacman`. For example, If you installed through `sudo pacman` then perhaps that's related.

**Comment by b1ackviking** [comment]
I have faced the same issue recently. If I install poetry with pacman or pip, I get permission denied. Solved by [installing poetry with pipx](https://python-poetry.org/docs/#installing-with-pipx).

**Comment by bbbart** [comment]
Okay, thanks for the advice. It probably makes sense, indeed, to install poetry through pip.

I tend to avoid using other package managers than my distro's "official" one, but an exception here can be made.

Thanks again!
